apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: radarr-public-route
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: public-ingress-gateway
      namespace: infra-network
  hostnames:
    - radarr.karafra.net
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ''
          kind: Service
          name: radarr-svc
          port: {{ .Values.radarr.service.port }}
          weight: 1
